services:
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - env-file.example
    command: echo "Hello world"
    ports:
      - 8000:8080
    depends_on:
      - database
  database:
    image: postgres:15.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - env-file.example
    ports:
      - 5434:5432
volumes:
  postgres_data:
