services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - env-file.example
    ports:
      - 8000:8080
    depends_on:
      - fileserver
      - database

  fileserver:
    build:
      context: ./fileserver
      dockerfile: Dockerfile
    volumes:
      - fileserver_data:/fileserver/data/
    env_file:
      - env-file.example
    ports:
      - 6432:80

  database:
    image: postgres:15.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - env-file.example

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - env-file.example
    ports:
      - 4173:80

volumes:
  postgres_data:
  fileserver_data:
