services:
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - env-file.example
    ports:
      - 8000:8080
    depends_on:
      - fileserver
      - test_fileserver
      - database
      - test_database

  database:
    image: postgres:15.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - env-file.example
    ports:
      - 5433:5432

  test_database:
    image: postgres:15.4-alpine
    volumes:
      - postgres_test_data:/var/lib/postgresql/data/
    env_file:
      - env-file.example
    ports:
      - 5434:5432

  fileserver:
    build:
      context: ./fileserver
      dockerfile: Dockerfile
    volumes:
      - fileserver_data:/fileserver/data/images
    env_file:
      - env-file.example
    ports:
      - 6432:80

  test_fileserver:
    build:
      context: ./fileserver
      dockerfile: Dockerfile
    volumes:
      - fileserver_test_data:/fileserver/data/images
    env_file:
      - env-file.example
    ports:
      - 6433:80

volumes:
  postgres_data:
  postgres_test_data:
  fileserver_data:
  fileserver_test_data:
