apiVersion: v1
kind: Service
metadata:
  name: fileserver
  labels:
    app: fileserver
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: fileserver

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fileserver
  labels:
    app: fileserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fileserver
  template:
    metadata:
      labels:
        app: fileserver
    spec:
      containers:
        - name: fileserver
          image: dqkqd/easy-recipes-fileserver:latest
          envFrom:
            - configMapRef:
                name: env-file-backend
          ports:
            - containerPort: 80
