from pathlib import Path

APP_DIR = Path(__file__).parent
STATIC_FOLDER = APP_DIR / "static"

DEFAULT_INGREDIENT_IMAGE_NAME = "default-ingredient-image.jpg"
DEFAULT_INGREDIENT_IMAGE = STATIC_FOLDER / DEFAULT_INGREDIENT_IMAGE_NAME

DEFAULT_RECIPE_IMAGE_NAME = "default-recipe-image.jpg"
DEFAULT_RECIPE_IMAGE = STATIC_FOLDER / DEFAULT_RECIPE_IMAGE_NAME
