"""Add likes column

Revision ID: 60b498e2afb2
Revises: de1b0cd7666e
Create Date: 2023-09-17 03:11:01.237596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "60b498e2afb2"
down_revision = "de1b0cd7666e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("recipes", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("likes", sa.Integer(), nullable=False, server_default="0")
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("recipes", schema=None) as batch_op:
        batch_op.drop_column("likes")

    # ### end Alembic commands ###
