"""Change image_url column into nullable.

Revision ID: b6d6938ba8b5
Revises: 5b88c50f7056
Create Date: 2023-08-20 04:37:46.950093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b6d6938ba8b5"
down_revision = "5b88c50f7056"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ingredients", schema=None) as batch_op:
        batch_op.alter_column("image_url", existing_type=sa.String(), nullable=True)

    with op.batch_alter_table("recipes", schema=None) as batch_op:
        batch_op.alter_column("image_url", existing_type=sa.String(), nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("recipes", schema=None) as batch_op:
        batch_op.alter_column("image_url", existing_type=sa.String(), nullable=False)

    with op.batch_alter_table("ingredients", schema=None) as batch_op:
        batch_op.alter_column("image_url", existing_type=sa.String(), nullable=False)

    # ### end Alembic commands ###
