"""Add likes column to ingredient.

Revision ID: ba10cdb4f7b5
Revises: 60b498e2afb2
Create Date: 2023-09-20 13:22:14.342285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ba10cdb4f7b5"
down_revision = "60b498e2afb2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ingredients", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("likes", sa.Integer(), nullable=False, server_default="0")
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ingredients", schema=None) as batch_op:
        batch_op.drop_column("likes")

    # ### end Alembic commands ###
