"""Remove name's uniqueness

Revision ID: c40048b46ab4
Revises: e8545b3bff81
Create Date: 2023-08-15 17:18:25.644694

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "c40048b46ab4"
down_revision = "e8545b3bff81"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ingredients", schema=None) as batch_op:
        batch_op.drop_constraint("ingredients_name_key", type_="unique")

    with op.batch_alter_table("recipes", schema=None) as batch_op:
        batch_op.drop_constraint("recipes_name_key", type_="unique")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("recipes", schema=None) as batch_op:
        batch_op.create_unique_constraint("recipes_name_key", ["name"])

    with op.batch_alter_table("ingredients", schema=None) as batch_op:
        batch_op.create_unique_constraint("ingredients_name_key", ["name"])

    # ### end Alembic commands ###
