"""Change image_url to image_uri

Revision ID: d2e387668857
Revises: b6d6938ba8b5
Create Date: 2023-08-20 04:50:51.178835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d2e387668857"
down_revision = "b6d6938ba8b5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ingredients", schema=None) as batch_op:
        batch_op.alter_column(column_name="image_url", new_column_name="image_uri")

    with op.batch_alter_table("recipes", schema=None) as batch_op:
        batch_op.alter_column(column_name="image_url", new_column_name="image_uri")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("recipes", schema=None) as batch_op:
        batch_op.alter_column(column_name="image_uri", new_column_name="image_url")

    with op.batch_alter_table("ingredients", schema=None) as batch_op:
        batch_op.alter_column(column_name="image_uri", new_column_name="image_url")

    # ### end Alembic commands ###
