"""Add name column.

Revision ID: e8545b3bff81
Revises: bc6cace70c50
Create Date: 2023-08-15 03:55:09.859756

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e8545b3bff81"
down_revision = "bc6cace70c50"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ingredients", schema=None) as batch_op:
        batch_op.add_column(sa.Column("name", sa.String(), nullable=False))
        batch_op.create_unique_constraint(None, ["name"])

    with op.batch_alter_table("recipes", schema=None) as batch_op:
        batch_op.add_column(sa.Column("name", sa.String(), nullable=False))
        batch_op.create_unique_constraint(None, ["name"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("recipes", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")
        batch_op.drop_column("name")

    with op.batch_alter_table("ingredients", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")
        batch_op.drop_column("name")

    # ### end Alembic commands ###
